-- Phase 1.5: Domain TXT verification workflow.
-- Adds verification status tracking to domains table.

ALTER TABLE domains
    ADD COLUMN verification_status VARCHAR(20) NOT NULL DEFAULT 'unverified',
    ADD COLUMN verification_token  VARCHAR(64);

-- Populate verification tokens for existing domains.
-- Using md5(id || name || now()) for uniqueness; new domains will get
-- tokens generated by the Go application.
UPDATE domains SET verification_token = md5(id::text || name || now()::text);

COMMENT ON COLUMN domains.verification_status IS 'Domain ownership verification state: unverified, pending, verified';
COMMENT ON COLUMN domains.verification_token IS 'Unique TXT record value for DNS-based domain ownership verification';
